### ISSUE TITLE
Crash - AndroidStringResource not parcelable?

### ISSUE THREAD

**Issue by yuraj11** [JulienArzul/SimpleDialogFragment#1]
Fatal Exception: java.lang.RuntimeException: Parcel: unable to marshal value AndroidStringResource{string=Do you want rate this app ?, resId=0}
       at android.os.Parcel.writeValue(Parcel.java:1455)
       at com.julienarzul.simpledialogfragment.AutoValue_SimpleDialogContent.writeToParcel(AutoValue_SimpleDialogContent.java:39)
       at android.os.Parcel.writeParcelable(Parcel.java:1474)
       at android.os.Parcel.writeValue(Parcel.java:1380)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:742)
       at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:148)
       at android.os.Parcel.writeTypedArray(Parcel.java:1285)
       at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:564)
       at android.os.Parcel.writeParcelable(Parcel.java:1474)
       at android.os.Parcel.writeValue(Parcel.java:1380)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:742)
       at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:150)
       at android.os.Parcel.writeTypedArray(Parcel.java:1285)
       at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:564)
       at android.os.Parcel.writeParcelable(Parcel.java:1474)
       at android.os.Parcel.writeValue(Parcel.java:1380)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
       at android.os.Bundle.writeToParcel(Bundle.java:1133)
       at android.os.Parcel.writeBundle(Parcel.java:742)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3622)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3974)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by JulienArzul** [comment]
Thank you.

Fixed in v1.1.1
